import type { Metadata } from "next";
import { Section } from "@/components/ui";

export const metadata: Metadata = {
  title: "Terms of Service",
};

export default function TermsPage() {
  return (
    <Section>
      <article className="prose prose-gray max-w-3xl mx-auto prose-headings:text-brand-dark">
        <h1>Terms of Service</h1>
        <p className="text-body-sm text-brand-gray-light">
          Last updated: April 16, 2026
        </p>

        <p>
          Welcome to the MYTE Technology website. By accessing or using this website, you agree
          to be bound by these Terms of Service. If you do not agree to these terms, please do
          not use this website.
        </p>

        <h2>Use of Website</h2>
        <p>
          This website is provided for informational purposes about MYTE Technology&rsquo;s
          managed IT and cybersecurity services. You agree to use this website only for lawful
          purposes and in a manner that does not infringe the rights of, restrict, or inhibit
          anyone else&rsquo;s use and enjoyment of the website.
        </p>
        <p>
          You may not use this website to transmit any harmful, threatening, abusive, or
          otherwise objectionable material, or to interfere with the proper working of the
          website.
        </p>

        <h2>Intellectual Property</h2>
        <p>
          All content on this website, including but not limited to text, graphics, logos, icons,
          images, and software, is the property of MYTE Technology or its content suppliers and
          is protected by United States and international copyright laws. Unauthorized
          reproduction, modification, distribution, or use of any content on this website is
          strictly prohibited without prior written consent from MYTE Technology.
        </p>

        <h2>Limitation of Liability</h2>
        <p>
          MYTE Technology shall not be liable for any direct, indirect, incidental, special,
          consequential, or punitive damages arising out of your access to, use of, or inability
          to use this website. This includes, without limitation, any errors or omissions in any
          content, or any loss or damage incurred as a result of the use of any content posted,
          transmitted, or otherwise made available via this website.
        </p>

        <h2>IT Cost Calculator Disclaimer</h2>
        <p>
          The IT Cost Calculator provided on this website is intended for informational and
          estimation purposes only. The results generated by the calculator are approximate and
          should not be relied upon as a precise quote or guarantee of pricing. Actual costs may
          vary based on your specific environment, requirements, and scope of services. MYTE
          Technology makes no warranties, express or implied, regarding the accuracy or
          completeness of calculator results. For an accurate assessment, please contact us for a
          personalized consultation.
        </p>

        <h2>Changes to Terms</h2>
        <p>
          MYTE Technology reserves the right to modify these Terms of Service at any time without
          prior notice. Changes will be effective immediately upon posting to this website. Your
          continued use of the website after any changes constitutes your acceptance of the
          revised terms. We encourage you to review these terms periodically.
        </p>

        <h2>Contact</h2>
        <p>
          If you have any questions about these Terms of Service, please contact us at{" "}
          <a href="mailto:legal@mytetech.com">legal@mytetech.com</a>.
        </p>
      </article>
    </Section>
  );
}
